/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tao_ndksearch_TestJni */

#ifndef _Included_com_tao_ndksearch_TestJni
#define _Included_com_tao_ndksearch_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tao_ndksearch_TestJni
 * Method:    funStatic
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_tao_ndksearch_TestJni_funStatic
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_tao_ndksearch_TestJni
 * Method:    fun
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_tao_ndksearch_TestJni_fun
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
