/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndkdemo_JniClient */

#ifndef _Included_com_example_ndkdemo_JniClient
#define _Included_com_example_ndkdemo_JniClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndkdemo_JniClient
 * Method:    printStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ndkdemo_JniClient_printStr
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
