/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndkdemo_JniClient */

#ifndef _Included_com_example_ndkdemo_JniClient
#define _Included_com_example_ndkdemo_JniClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndkdemo_JniClient
 * Method:    printStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ndkdemo_JniClient_printStr
  (JNIEnv *, jclass);

/*
 * Class:     com_example_ndkdemo_JniClient
 * Method:    addInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_ndkdemo_JniClient_addInt
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_ndkdemo_JniClient
 * Method:    printUser
 * Signature: (Lcom/example/ndkdemo/User;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ndkdemo_JniClient_printUser
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_example_ndkdemo_JniClient
 * Method:    createUser
 * Signature: (Ljava/lang/String;ILjava/lang/String;)Lcom/example/ndkdemo/User;
 */
JNIEXPORT jobject JNICALL Java_com_example_ndkdemo_JniClient_createUser
  (JNIEnv *, jclass, jstring, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
