/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bither_util_Test */

#ifndef _Included_net_bither_util_Test
#define _Included_net_bither_util_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bither_util_Test
 * Method:    printMyHelloWorld
 * Signature: (Landroid/graphics/Bitmap;III[BZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bither_util_Test_printMyHelloWorld
  (JNIEnv *, jclass, jobject, jint, jint, jint, jbyteArray, jboolean);

#ifdef __cplusplus
}
#endif
#endif
