/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_skyworthauto_testjni_TestJni */

#ifndef _Included_com_skyworthauto_testjni_TestJni
#define _Included_com_skyworthauto_testjni_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_skyworthauto_testjni_TestJni
 * Method:    funStatic
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_skyworthauto_testjni_TestJni_funStatic
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_skyworthauto_testjni_TestJni
 * Method:    fun
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_skyworthauto_testjni_TestJni_fun__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_skyworthauto_testjni_TestJni
 * Method:    fun
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_com_skyworthauto_testjni_TestJni_fun__FF
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_skyworthauto_testjni_TestJni
 * Method:    createObject
 * Signature: ()Lcom/skyworthauto/testjni/JavaObject;
 */
JNIEXPORT jobject JNICALL Java_com_skyworthauto_testjni_TestJni_createObject
  (JNIEnv *, jobject);

/*
 * Class:     com_skyworthauto_testjni_TestJni
 * Method:    createObjectAndSet
 * Signature: ()Lcom/skyworthauto/testjni/JavaObject;
 */
JNIEXPORT jobject JNICALL Java_com_skyworthauto_testjni_TestJni_createObjectAndSet
  (JNIEnv *, jobject);

/*
 * Class:     com_skyworthauto_testjni_TestJni
 * Method:    getField
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_skyworthauto_testjni_TestJni_getField
  (JNIEnv *, jobject);

/*
 * Class:     com_skyworthauto_testjni_TestJni
 * Method:    getStaticField
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_skyworthauto_testjni_TestJni_getStaticField
  (JNIEnv *, jobject);

/*
 * Class:     com_skyworthauto_testjni_TestJni
 * Method:    invokeMethod
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_skyworthauto_testjni_TestJni_invokeMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_skyworthauto_testjni_TestJni
 * Method:    invokeStaticMethod
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_skyworthauto_testjni_TestJni_invokeStaticMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
