/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tao_wei_testjni_ShellHolderView */

#ifndef _Included_com_tao_wei_testjni_ShellHolderView
#define _Included_com_tao_wei_testjni_ShellHolderView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tao_wei_testjni_ShellHolderView
 * Method:    nativeAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_tao_wei_testjni_ShellHolderView_nativeAdd__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_tao_wei_testjni_ShellHolderView
 * Method:    nativeAdd
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_com_tao_wei_testjni_ShellHolderView_nativeAdd__FF
  (JNIEnv *, jobject, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
